version: "3.9"
services:
  api:
    build: .
    ports:
      - "5000:5000"
    environment:
      WEB_PORT: "5000"
      DB_URL: "mongodb://mongo:27017/?readPreference=primary&appname=MongoDB%20Compass&ssl=false"
      DB_NAME: "linkShortener"
      DB_URL_COLLECTION: "urls"
      BASE_URL: "http://192.168.1.150:5000/"
  mongo:
    image: mongo
    command: --noscripting